### PR TITLE
User profile image support

### PR DESCRIPTION
**Pull request by nitinseshadri**
See the individual commits for more info.

### CODE REVIEW

**Comment by Shiryou** [comment]
Is there a good reason for not squashing this into a single commit?

**Comment by nitinseshadri** [comment]
The first commit was intended to be final; however I botched the eJS comments (twice!), and only realized it later.

**Comment by Shiryou** [comment]
I think it would be best to [squash this into a single commit](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) to keep the repository history clean.

**Comment by nitinseshadri** [comment]
Let's wait on this.

_Closed._

**Pull request closed without merging**
