### PR TITLE
Changed "Search" text in search button to a search icon glyph

### PR DESCRIPTION
**Pull request by lpraz**
Resolves issue #20 by changing the "Search" text on the button for the search field in the header to the `search` glyph provided by Google's Material Icons.
This, of course, shouldn't be merged right away if another set of glyphs, such as Font Awesome, should be used instead. Let me know if that is the case, and I will make the appropriate modifications.

### CODE REVIEW

**Comment by NattyNarwhal** [comment]
Nitpicking: I don't really see the point is changing to a button glyph unless you can make the search glyph inside of the search box itself, if you know what I mean..

**Comment by nitinseshadri** [comment]
Like a "linked" search bar and button?

**Comment by lpraz** [comment]
As in, remove the button entirely and have a search box that's entirely blank, except for a (probably clickable) "search" glyph inside it?

**Comment by nitinseshadri** [comment]
@NattyNarwhal If I understand correctly, this 'linked' search bar can be done using a Bootstrap input group. See https://github.com/nitinseshadri/adventure/tree/ns-enhancements for how I did it.

**Pull request closed without merging**
